Bleeding Emscripten Fixes  (#352)
* Fixes for Addons / FreeType add platforms

* OpenSSL 3.2.1

* FreeImage LibPNG Patches

* LibPNG [1.6.40] -> [1.6.42]

* Merge

* libpng other platform fixes

* Emscripten Fixes for LibPNG / Zlib WASM

* Cache clean

* zlib [1.3.01]->[1.3.1]

* LibPNG 1.6.43 patched fixes for emscripten

* Emscripten

* LibPNG not sure why bot not doing this correctly

* Fmt cmake update

* fmt master emscripten cmake updated

* Emscripten GitHub Actions

* LibPNG 1.6.42 cmake

* Emscripten and fmt fix

* Emscripten / freetype fixes / svgtiny

* Emscripten FreeType / Libxml2 / svgtiny

* Emscripten uriparser / libxml2 fixes

* libxml2 fixes and svgtiny

* Fix VS uriparser / copy svgtiny wasm

* SVG Tiny copy

* Emscripten

* uriparser no install

* Revert "uriparser no install"

This reverts commit b39fa7de13807f1f23353f0be0e2f2582791b0e4.

* Release Copy fix

* Update Copy to write out version info

* Fixing CMakeCache issues. Added Secure Version Info to all

* Secure script / fix glew / libpng

* Apothecary Platform fix

* RTAudio fix cache

* OpenCV fix mac catalyst

* SSL Git url

* shfmt

* svgtiny release vs

* Format Style

* Fix missing libusb

* Test Workflow Run Depend

* cairo zip for windows

* Assimp copy fix

* OpenSSL off while fixing

* macOS Brotli off for now

* Secure version info just in pkl

* Brotli

* Readme update

* OpenSSL 3 changes

* Fix OpenSSL 3

* OpenSSL arm64/ec patched cmake

* OpenSSL depend zlib

* OpenSSL 3 Complete

* OpenSSL / Curl

* OpenSSL tvOS fix. Curl no copy cmakelist use updated in github repo version

* OpenSSL Disabled for tvos / watchos for moment reported upstream

* Curl - Fix sockets, ipv6 enabled, threaded resolver

* Libsocket off curl apple

* Remove catos

diff --git a/apothecary/apothecary b/apothecary/apothecary
--- a/apothecary/apothecary
+++ b/apothecary/apothecary
@@ -61,6 +61,8 @@ BUILD_DIR=
 # full path to the destination dir for compiled libs
 LIBS_DIR=""
 
+DEPEND_DIR=""
+
 # number of parallel tasks to run on make.
 # formulas should pass this as -j${PARALLEL_MAKE} to make
 PARALLEL_MAKE=1
@@ -70,6 +72,7 @@ SAVE_SCRIPT="$(realpath "$APOTHECARY_DIR/../scripts/save.sh")"
 LOAD_SCRIPT="$(realpath "$APOTHECARY_DIR/../scripts/load.sh")"
 SAVE_FILE="$(realpath "$APOTHECARY_DIR/../scripts")/status.txt"
 SECURE_SCRIPT="$(realpath "$APOTHECARY_DIR/../scripts/secure.sh")"
+FORMAT_SCRIPT="$(realpath "$APOTHECARY_DIR/../scripts/format.sh")"
 
 USE_SAVE=0
 
@@ -486,10 +489,10 @@ if [ "$TYPE" = "vs" ]; then
         MULTITHREADED_TYPE="MD"
     fi
     if [ $MULTITHREADED_TYPE == "MD" ]; then
-        MT_TYPE="/MD"
+        export MT_TYPE="/MD"
         echoVerbose "MULTITHREADED_TYPE MD"
     elif [ $MULTITHREADED_TYPE == "MT" ]; then
-        MT_TYPE="/MT"
+        export MT_TYPE="/MT"
         echoVerbose "MULTITHREADED_TYPE MT"
     fi
 
@@ -670,6 +673,7 @@ if [ "$TYPE" = "emscripten" ]; then
     export FLAG_RELEASE="-O3"
 	EMSCRIPTEN_SCRIPT="$(realpath "$APOTHECARY_DIR/../scripts/emscripten/setup.sh")"
 	. "$EMSCRIPTEN_SCRIPT"
+    PLATFORM=WASM
 fi
 
 if [ "$TYPE" = "ios" ]; then
@@ -752,6 +756,7 @@ if [ "$TYPE" == "linux" ] || [ "$TYPE" == "linux64" ] || [ "$TYPE" == "linuxaarc
     elif [ $TYPE == "msys2" ]; then
         ABI="x86_64"
     fi 
+    PLATFORM=ABI
 fi
 
 
@@ -785,6 +790,40 @@ fi
 	export PATH="$VS_BIN_PATH:$PATH"
 
  fi
+
+get_directory_path() {
+    local type="$1"
+    local base_dir="$2"
+    local platform="$3"
+    local abi="$4"
+    local final_path=""
+
+    case "$type" in
+        vs)
+            final_path="${base_dir}/lib/${type}/${platform}/"
+            ;;
+        osx|ios|tvos|xros|catos|watchos)
+            final_path="${base_dir}/lib/${type}/${platform}/"
+            ;;
+        emscripten)
+            final_path="${base_dir}/lib/${type}/"
+            ;;
+        linux64|linux|msys2)
+            final_path="${base_dir}/lib/${type}/"
+            ;;
+        android)
+            final_path="${base_dir}/lib/${type}/${abi}/"
+            ;;
+        *)
+            echo "Unsupported type: $type" >&2
+            return 1  # Return with error if type is unsupported
+            ;;
+    esac
+
+    echo "$final_path"  # This will be the function's return value
+}
+
+
 
 ################################################################################
 ### FUNCTIONS
@@ -1654,6 +1693,10 @@ function apothecaryDepend() {
         return
     fi
 
+    # Capture the returned path into a variable
+    DIRECTORY_PATH=$(get_directory_path "$TYPE" "$1" "$PLATFORM" "$ARCH")
+    echo "Presumed directory path: $DIRECTORY_PATH"
+
     # Use git if the USE_GIT variable is set
     if [ $FORCE_DOWNLOAD -eq 1 ]; then
         $APOTHECARY_SCRIPT -f -t $TYPE -a $ARCH -j$PARALLEL_MAKE ${USE_GIT:+-g} $1 $depend
@@ -1777,6 +1820,7 @@ echoVerbose "Build dir: $BUILD_DIR"
 # use default libs dir?
 if [ -z "${CUSTOM_LIBS_DIR+x}" ] ; then
 	export LIBS_DIR=$REL_LIBS_DIR
+    export REAL_LIBS_DIR=$REL_LIBS_DIR
     export IS_CUSTOM_LIBS_DIR=0
     echoVerbose "CUSTOM_LIBS_DIR is empty: $LIBS_DIR REL_LIBS_DIR:$REL_LIBS_DIR"
 else # manually set
@@ -1784,6 +1828,8 @@ else # manually set
 		/*) export LIBS_DIR=$CUSTOM_LIBS_DIR ;; # absolute path
 	 	*) export LIBS_DIR=$WD/$CUSTOM_LIBS_DIR ;; # relative path
 	esac
+    export REAL_LIBS_DIR=$REL_LIBS_DIR
+    export REAL_LIBS_DIR=$REL_LIBS_DIR
 	export IS_CUSTOM_LIBS_DIR=1
     echoVerbose "CUSTOM_LIBS_DIR is set: $LIBS_DIR custom:$CUSTOM_LIBS_DIR"
 fi
@@ -1829,11 +1875,10 @@ if [[ "$TYPE" == "android" ]] ; then
 		ABI=""
 		echoError "Targeting android, ARCH not set! Please use -a arm64"
 	fi
+    PLATFORM=ABI
 else 
 	ABI=""
 fi
-
-
 
 CROSSCOMPILING=0
 if [ "$TYPE" == "linuxarmv6l" ] || [ "$TYPE" == "linuxaarch64" ] || [ "$TYPE" == "linuxarmv7l" ]; then
