Updated Scripts for Windows SDK change easily

diff --git a/apothecary/apothecary b/apothecary/apothecary
--- a/apothecary/apothecary
+++ b/apothecary/apothecary
@@ -119,6 +119,8 @@ NDK_VERSION_MAJOR=24
 ANDROID_API=21
 ANDROID_PLATFORM=android-${ANDROID_API}
 
+
+
 ################################################################################
 ### PRIVATE VARS, for internal use
 ### DEFINITELY READ ONLY!
@@ -176,7 +178,9 @@ USE_GIT=
 # by default assume visual studio pro
 # -x changes to visual studio express
 VS_BUILD_TOOL=devenv
-
+WIN10_INSTALLED_SDK_2019=10.0.190410.0
+WIN10_INSTALLED_SDK_2022=10.0.20348.0
+WIN11_INSTALLED_SDK_2022=10.0.22621.0
 VS_TYPE=Community
 
 # nice, detailed help message
@@ -351,23 +355,113 @@ while getopts t:a:b:d:s:j:hgvfpe opt ; do
 done
 shift $(expr $OPTIND - 1)
 
+function setup_vs_vars(){
+    
+    #2019 and onwards we need to pass the platform as the arg
+    if [ $VS_VER -gt 15 ] ; then
+        # we want to make sure that the build command is called with the correct environment variables set up
+        # we achieve this by piping all commands into a .bat file and then calling this temporary .bat file.
+
+        echo "-- Searching for vs-build"
+        #cmd.exe //C """$VS_VARS_PATH $PLATFORM"""
+
+        echo "-- Searching for vs-build2"
+        # vswhere is a utility to find the most recent vs compiler toolchain. it is
+        # assumed to be installed at a fixed location
+        if [ $VS_VER == 15 ] ; then
+            VSWHERE_EXE=`cmd.exe //c "echo %ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"`
+        elif [ $VS_VER == 16 ] ; then
+            VSWHERE_EXE=`cmd.exe //c "echo %ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"`
+        elif [ $VS_VER -gt 17 ] ; then
+            VSWHERE_EXE=`cmd.exe //c "echo %ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"`
+        else
+            VSWHERE_EXE=`cmd.exe //c "echo %ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"`
+        fi
+
+        echo "-- Found vswhere: ${VSWHERE_EXE}"
+        # vswhere allows us to query the install dir of the ms build tools
+        VS_INSTALL_PATH=`cmd //c "${VSWHERE_EXE}" -latest -products Microsoft.VisualStudio.Product.${VS_TYPE} -requires Microsoft.VisualStudio.Component.VC.CoreIde -property installationPath`
+        echo "-- Found vs install path: ${VS_INSTALL_PATH}"
+        # msbuild is the tool used to build visual studio solutions
+        MSBUILD_PATH="${VS_INSTALL_PATH}\MSBuild\\${VS_VER}.0\Bin\MSBuild.exe"
+        echo "-- Found MSBuild path: ${MSBUILD_PATH}"
+
+        VS_VER_DIR=$(ls "$VS_BASE_PATH/VC/Tools/MSVC/" | tail -1)
+        if [ $ARCH == "arm64" ] || [ $ARCH == "ARM" ]; then
+            export VS_BIN_PATH="$VS_BASE_PATH/VC/Tools/MSVC/$VS_VER_DIR/bin/$VS_HOSTPLATFORM/$BUILD_PLATFORM"
+        else 
+            export VS_BIN_PATH="$VS_BASE_PATH/VC/Tools/MSVC/$VS_VER_DIR/bin/$VS_HOSTPLATFORM/$BUILD_PLATFORM"
+        fi
+
+        echo "VS_BIN_PATH was not set - setting to $VS_BIN_PATH"
+
+        export PATH=$VS_BIN_PATH:$PATH
+
+
+        (
+            # with parentheses we open a new sub-shell scope to make sure we're not overwriting any presets for IFS
+            # set input field separator to colon (:) for current scope
+            IFS=:
+            for vs_bin_directory in ${VS_BIN_PATH}; do
+                # we must make sure each given directory exists
+                if [ ! -d ${vs_bin_directory} ]; then
+                    echo "Couldn't confirm Visual Studio path exists: '$vs_bin_directory', probably installed on a non standard location?"
+                    exit 1
+                else
+                    echo "Confirmed VS_BIN_PATH element exists: '${vs_bin_directory}'"
+                fi
+
+            done
+        )
+
+    fi
+     
+}
+
+function with_vs_env(){
+    
+    #2019 and onwards we need to pass the platform as the arg
+    if [ $VS_VER -gt 15 ] ; then
+        # we want to make sure that the build command is called with the correct environment variables set up
+        # we achieve this by piping all commands into a .bat file and then calling this temporary .bat file.
+
+        echo "" > with_env.bat # cleanup temporary bat file
+        echo "call \"$VS_VARS_PATH\" $PLATFORM && $@" >> with_env.bat
+        cmd.exe //C "call with_env.bat"
+    elif [ $VS_VER == 15 ] ; then
+        # we want to make sure that the build command is called with the correct environment variables set up 
+        # we achieve this by piping all commands into a .bat file and then calling this temporary .bat file.
+
+        echo "" > with_env.bat # cleanup temporary bat file
+        echo "call \"$VS_VARS_PATH\" && $@" >> with_env.bat
+        cmd.exe //C "call with_env.bat"
+    else
+        #statements
+        echo "older"
+        if [ $ARCH == 32 ] ; then
+            cmd.exe \/c "call \"%VS${VS_VER}0COMNTOOLS%vsvars32.bat\" && $@"
+        elif [ $ARCH == 64 ] ; then
+            cmd.exe \/c "call \"%VS${VS_VER}0COMNTOOLS%..\\..\\${VS_64_BIT_ENV}\" && $@"
+        fi
+    fi
+}
+
+
 
 # used when building for vs - set to 16 if not set explicitly
 if [ "$TYPE" = "vs" ]; then
+
     if [ -z ${VS_VER+x} ]; then 
-	    echo "VS_VER was not set - setting to 16"
-	    VS_VER=16 #17 	
+           
         if [ $ARCH == "arm64" ]; then
-            VS_VER=17
-        fi 
-    else 
-        if [ $ARCH == "arm64" ]; then
+            echo "VS_VER was not set - setting to 17 arm64"
             VS_VER=17
         else
-            echo "VS_VER is set to '$VS_VER'"
-            VS_VER_GEN="$VS_VER 2019"
-        fi
+            echo "VS_VER was not set - setting to 16"
+            VS_VER=16 #17  
+        fi 
     fi
+
 
     VS_64_BIT_ENV='VC\vcvarsall'
 
@@ -401,10 +495,12 @@ if [ "$TYPE" = "vs" ]; then
     	VS_YEAR=2022
     	VS_VER=17
     	VS_VER_GEN="$VS_VER $VS_YEAR"
+        export CMAKE_WIN_SDK="-DCMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION=${WIN10_INSTALLED_SDK_2022} -DCMAKE_SYSTEM_VERSION=${WIN10_INSTALLED_SDK_2022}"
     else
     	VS_YEAR=2019
     	VS_VER=16
     	VS_VER_GEN="$VS_VER $VS_YEAR"
+        export CMAKE_WIN_SDK="-DCMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION=${WIN10_INSTALLED_SDK_2019} -DCMAKE_SYSTEM_VERSION=${WIN10_INSTALLED_SDK_2019}"
 	fi    
 
 	echo "PLATFORM set to ${PLATFORM} Visual Studio ${VS_VER_GEN} - ${CROSS_TOOL} - ${VS_HOST}"
@@ -413,10 +509,16 @@ if [ "$TYPE" = "vs" ]; then
 
     if [ -z "${WSL_DISTRO_NAME+x}" ]
 	then
-		DRIVE=/c/
+		DRIVE=/c
 	else
-	  	DRIVE=/mnt/c/
+	  	DRIVE=/mnt/c
 	fi 
+
+    if [ -z ${VS_HOSTPLATFORM+x} ]; then
+        VS_HOSTPLATFORM=Hostx64
+    #else
+    #    VS_HOSTPLATFORM=Hostx64
+    fi
 
 
     if [ -z ${VS_BASE_PATH+x} ]; then
@@ -444,15 +546,38 @@ if [ "$TYPE" = "vs" ]; then
             	VS_YEAR=$VS_YEAR_PATH
         	# fi
         elif [ "${VS_VER}" = "17" ]; then
+
           	VS_BASE_PATH="${DRIVE}/Program Files/Microsoft Visual Studio/2022/$VS_TYPE"
           	VS_YEAR=2022
           	VC_VERSION=143
+            VS_BAT="vcvars$ARCH.bat"
+             #VS_BASE_PATH="${DRIVE}/Program Files (x86)/Microsoft Visual Studio/$VS_YEAR_PATH/$VS_TYPE"
         fi
     fi
+
+    if [ $ARCH == 32 ] ; then
+        BUILD_PLATFORM="x86"
+    elif [ $ARCH == 64 ] ; then
+        BUILD_PLATFORM="x64"
+    elif [ $ARCH == "arm64" ] ; then
+        BUILD_PLATFORM="arm64"
+    elif [ $ARCH == "arm" ]; then
+        BUILD_PLATFORM="arm"
+    fi 
+
+    if [ $ARCH == 32 ] ; then
+        PLATFORM="Win32"
+    elif [ $ARCH == 64 ] ; then
+        PLATFORM="x64"
+    elif [ $ARCH == "arm64" ] ; then
+        PLATFORM="ARM64"
+    elif [ $ARCH == "arm" ]; then
+        PLATFORM="ARM"
+    fi 
 	
 
 
-	if [ $ARCH == "arm64" ] || [ $ARCH == "ARM" ] ; then
+	if [ $ARCH == "arm64" ] || [ $ARCH == "ARM" ]; then
            
 		VS_VARS_PATH=$(cygpath -wa "$VS_BASE_PATH/VC/Auxiliary/Build/vcvarsall.bat")
 
@@ -461,14 +586,32 @@ if [ "$TYPE" = "vs" ]; then
 
 	fi
 
+    echo "VS_VARS_PATH: $VS_VARS_PATH"
 
-	export VS_BASE_PATH; 
-	export VS_VARS_PATH;
-    export VS_YEAR;
+    #setup_vs_vars 
+    #cmd.exe \/c "call \"%VS${VS_VER}0COMNTOOLS%..\\..\\${VS_64_BIT_ENV}\" amd64 && $@"
+
+    # echo "vspath:$VS_BASE_PATH"
+    #echo "vspath:$VS_VARS_PATH"
+    #cmd.exe \/c "call \"${VS_VARS_PATH}\""
+
+
+	#export VS_BASE_PATH; 
+	#export VS_VARS_PATH;
+    #export VS_YEAR;
+
 
     if [ -z ${VS_BIN_PATH+x} ]; then	            
 		VS_VER_DIR=$(ls "$VS_BASE_PATH/VC/Tools/MSVC/" | tail -1)
-        VS_BIN_PATH="$VS_BASE_PATH/VC/Tools/MSVC/$VS_VER_DIR/bin/Host$PLATFORM/$PLATFORM"
+
+        if [ $ARCH == "arm64" ] || [ $ARCH == "ARM" ]; then
+            export VS_BIN_PATH="$VS_BASE_PATH/VC/Tools/MSVC/$VS_VER_DIR/bin/$VS_HOSTPLATFORM/$BUILD_PLATFORM"
+        else 
+            export VS_BIN_PATH="$VS_BASE_PATH/VC/Tools/MSVC/$VS_VER_DIR/bin/$VS_HOSTPLATFORM/$BUILD_PLATFORM"
+        fi
+
+        
+        echo "VS_BIN_PATH was not set - setting to $VS_BIN_PATH"
 
 		export PATH=$VS_BIN_PATH:$PATH
 
@@ -488,7 +631,7 @@ if [ "$TYPE" = "vs" ]; then
 	        done
         )
 
-        echo "VS_BIN_PATH was not set - setting to $VS_BIN_PATH"
+        
 
         # Test for existence of directory where cmake should live
         # then prepend cmake path to PATH
@@ -496,16 +639,9 @@ if [ "$TYPE" = "vs" ]; then
             export PATH="/c/Program Files/CMake/bin/:$PATH"
         fi
     fi
-
-    if [ $ARCH == 32 ] ; then
-        PLATFORM="Win32"
-    elif [ $ARCH == 64 ] ; then
-        PLATFORM="x64"
-    elif [ $ARCH == "arm64" ] ; then
-        PLATFORM="ARM64"
-    elif [ $ARCH == "arm" ]; then
-        PLATFORM="ARM"
-    fi 
+    #echo "PATH: $PATH"
+    #PATH="/c/Program Files/CMake/bin:/c/windows;/c/windows/system32:/c/windows/system32/Wbem:$VS_BIN_PATH:/c/Program Files/Git/cmd:/c/Windows/System32/WindowsPowerShell/v1.0:/mingw32/bin:/usr/local/bin:/usr/bin:/bin:/mingw32/bin:/usr/bin:/"
+    #echo "NEW PATH: $PATH"
 fi
 
 if [ "$TYPE" = "emscripten" ]; then
@@ -1108,32 +1244,6 @@ function gitclone() {
 	}
 }
 
-function with_vs_env(){
-	
-    #2019 and onwards we need to pass the platform as the arg
-    if [ $VS_VER -gt 15 ] ; then
-		# we want to make sure that the build command is called with the correct environment variables set up
-		# we achieve this by piping all commands into a .bat file and then calling this temporary .bat file.
-
-		echo "" > with_env.bat # cleanup temporary bat file
-		echo "call \"$VS_VARS_PATH\" $PLATFORM && $@" >> with_env.bat
-		cmd.exe //C "call with_env.bat"
-    elif [ $VS_VER == 15 ] ; then
-		# we want to make sure that the build command is called with the correct environment variables set up 
-		# we achieve this by piping all commands into a .bat file and then calling this temporary .bat file.
-
-		echo "" > with_env.bat # cleanup temporary bat file
-		echo "call \"$VS_VARS_PATH\" && $@" >> with_env.bat
-		cmd.exe //C "call with_env.bat"
-	else
-		#statements
-		if [ $ARCH == 32 ] ; then
-			cmd.exe \/c "call \"%VS${VS_VER}0COMNTOOLS%vsvars32.bat\" && $@"
-		elif [ $ARCH == 64 ] ; then
-	        cmd.exe \/c "call \"%VS${VS_VER}0COMNTOOLS%..\\..\\${VS_64_BIT_ENV}\" amd64 && $@"
-		fi
-	fi
-}
 
 # visual studio builder
 # args: <"path/to/sol.sln"> [action] [config]
@@ -1165,37 +1275,29 @@ function vs-build() {
 		echo "-- Found MSBuild path: ${MSBUILD_PATH}"
 
 		# define fallback build selection if vs-build was not called with enough parameters.
-		if [ $VS_VER == 15 ] ; then
-			if [ $ARCH == 32 ] ; then
-				DEFAULT_BUILD="Release|Win32"
-			elif [ $ARCH == 64 ] ; then
-				DEFAULT_BUILD="Release|x64"
-			elif [ $ARCH == "arm64" ] ; then
-				DEFAULT_BUILD="Release|ARM"
-			fi
-		else # 2019/2022
-			if [ $ARCH == 32 ] ; then
-				DEFAULT_BUILD="Release|Win32"
-			elif [ $ARCH == 64 ] ; then
-				DEFAULT_BUILD="Release|x64"
-			elif [ $ARCH == "ARM" ] ; then
-				DEFAULT_BUILD="Release|ARM"
-			elif [ $ARCH == "arm64" ] ; then
-				DEFAULT_BUILD="Release|ARM64"
-			fi
+		
+		if [ $ARCH == 32 ] ; then
+			DEFAULT_BUILD="Release|Win32"
+		elif [ $ARCH == 64 ] ; then
+			DEFAULT_BUILD="Release|x64"
+		elif [ $ARCH == "ARM" ] ; then
+			DEFAULT_BUILD="Release|ARM"
+		elif [ $ARCH == "arm64" ] ; then
+			DEFAULT_BUILD="Release|ARM64"
 		fi
+	
 
 		# Cut part before '|' character of third parameter (which defaults to "Default|x64") and store it as BUILD_CONFIGURATION
 		BUILD_CONFIGURATION="$( cut -d '|' -f 1 <<< "${3:-$DEFAULT_BUILD}" )"
 		BUILD_CONFIGURATION=$BUILD_CONFIGURATION
-		# Cut part after '|' character of third parameter (which defaults to "Default|x64") and store it as BUILD_PLATFORM
-		BUILD_PLATFORM="$( cut -d '|' -f 2- <<< "${3:-$DEFAULT_BUILD}" )"
-		BUILD_PLATFORM=$BUILD_PLATFORM
+		# Cut part after '|' character of third parameter (which defaults to "Default|x64") and store it as VS_BUILD_PLATFORM
+		VS_BUILD_PLATFORM="$( cut -d '|' -f 2- <<< "${3:-$DEFAULT_BUILD}" )"
+		VS_BUILD_PLATFORM=$VS_BUILD_PLATFORM
 
-		echo "-- Build platform: $BUILD_PLATFORM"
+		echo "-- Build platform: $VS_BUILD_PLATFORM"
 		echo "-- Build configuration: $BUILD_CONFIGURATION"
 
-		BUILD_EXEC="\"MSBuild.exe\" \"$1\" /t:${2:-Build} /p:Platform=\"$BUILD_PLATFORM\" /p:Configuration=\"$BUILD_CONFIGURATION\""
+		BUILD_EXEC="\"MSBuild.exe\" \"$1\" /t:${2:-Build} /p:Platform=\"$VS_BUILD_PLATFORM\" /p:Configuration=\"$BUILD_CONFIGURATION\""
 		echo "-- Build parameters: $BUILD_EXEC"
 
 		# we need to add some extra outer quotes, since cmd.exe will only remove the outermost quotes and we might
